version: "3"

services:
  datastep-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: bash -c "
      cd /app/src
      && python -m alembic upgrade head
      && cd /
      && python3 /app/src/app.py"
    ports:
      - "8080:8080"
    environment:
      #      - OPENAI_API_KEY=${OPENAI_API_KEY}
      #      - OPENAI_API_BASE=${OPENAI_API_BASE}

      - AZURE_DEPLOYMENT_NAME_DB_ASSISTANT=${AZURE_DEPLOYMENT_NAME_DB_ASSISTANT}
      - AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES=${AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES}
      - AZURE_DEPLOYMENT_NAME_EMBEDDINGS=${AZURE_DEPLOYMENT_NAME_EMBEDDINGS}

      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}

      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}

      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
      - FASTEMBED_CACHE_PATH=${FASTEMBED_CACHE_PATH}
    volumes:
      - server:${DATA_FOLDER_PATH}

  datastep-redis-server:
    image: redis/redis-stack-server
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6379:6379"
    volumes:
      - redis-server:${DATA_FOLDER_PATH}

  datastep-rq-worker:
    image: datastep_backend
    restart: always
    command: rq worker --path /app/src --url redis://:${REDIS_PASSWORD}@${REDIS_HOST}:6379 mapping_nomenclatures sync_nomenclatures retrain_classifier classification documents
    environment:
      #      - OPENAI_API_KEY=${OPENAI_API_KEY}
      #      - OPENAI_API_BASE=${OPENAI_API_BASE}

      - AZURE_DEPLOYMENT_NAME_DB_ASSISTANT=${AZURE_DEPLOYMENT_NAME_DB_ASSISTANT}
      - AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES=${AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES}
      - AZURE_DEPLOYMENT_NAME_EMBEDDINGS=${AZURE_DEPLOYMENT_NAME_EMBEDDINGS}

      - AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - AZURE_OPENAI_ENDPOINT=${AZURE_OPENAI_ENDPOINT}
      - OPENAI_API_VERSION=${OPENAI_API_VERSION}

      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}

      - CHROMA_HOST=${CHROMA_HOST}
      - CHROMA_PORT=${CHROMA_PORT}

      - DATA_FOLDER_PATH=${DATA_FOLDER_PATH}
      - FASTEMBED_CACHE_PATH=${FASTEMBED_CACHE_PATH}
    volumes:
      - server:${DATA_FOLDER_PATH}

  datastep-db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - datastep-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  datastep-dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - datastep-dbeaver:/opt/cloudbeaver/workspace
    ports:
      - "8978:8978"

  datastep-chroma-db:
    image: chromadb/chroma
    restart: always
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8001:8000"

volumes:
  server:
  redis-server:
  datastep-db:
  datastep-dbeaver:
  chroma-data:
    driver: local

