version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: bash -c "
      cd /app/src
      && python -m alembic upgrade head
      && python3 /app/src/app.py"
    ports:
      - "8090:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      # Just to see .env in files viewer
      - ./.env:${DATA_FOLDER_PATH}/env-file
      - backend:${DATA_FOLDER_PATH}

  redis-server:
    image: redis/redis-stack-server
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6389:6379"
    volumes:
      - redis-server:${DATA_FOLDER_PATH}

  rq-worker:
    image: datastep_backend
    restart: always
    command: rq worker --path /app/src --url redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT} mapping_nomenclatures sync_nomenclatures retrain_classifier classification documents
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - backend:${DATA_FOLDER_PATH}
    depends_on:
      - backend
      - redis-server

volumes:
  backend:
  redis-server:
