version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    command: bash -c "
      cd /app/src
      && python -m alembic upgrade head
      && python3 /app/src/app.py"
    ports:
      - "8090:8080"
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - server:${DATA_FOLDER_PATH}

  redis-server:
    image: redis/redis-stack-server
    restart: always
    command: bash -c "redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}"
    ports:
      - "6389:6379"
    volumes:
      - redis-server:${DATA_FOLDER_PATH}

  rq-worker:
    image: datastep-backend
    restart: always
    command: rq worker --path /app/src --url redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT} mapping_nomenclatures sync_nomenclatures retrain_classifier classification documents
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
      - server:${DATA_FOLDER_PATH}
    depends_on:
      - redis-server

  rq-dashboard:
    image: eoranged/rq-dashboard
    ports:
      - "9181:9181"
    environment:
      - RQ_DASHBOARD_REDIS_URL=redis://:${REDIS_PASSWORD}@${REDIS_HOST}:${REDIS_PORT}
    depends_on:
      - redis-server

  db:
    image: postgres
    restart: always
    ports:
      - "5442:5432"
    volumes:
      - datastep-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  dbeaver:
    image: dbeaver/cloudbeaver
    restart: always
    volumes:
      - datastep-dbeaver:/opt/cloudbeaver/workspace
    ports:
      - "8988:8978"

  volumes-viewer:
    image: filebrowser/filebrowser
    ports:
      - "9080:80"
    volumes:
      - server:/srv

  chroma-db:
    image: chromadb/chroma
    restart: always
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - chroma-data:/chroma/chroma/
    ports:
      - "8011:8000"

volumes:
  server:
  redis-server:
  datastep-db:
  datastep-dbeaver:
  chroma-data:
    driver: local
