"""new classifier config params

Revision ID: 078a8a1568f6
Revises: f79c428cf17b
Create Date: 2024-07-13 01:47:11.288720

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '078a8a1568f6'
down_revision: Union[str, None] = 'f79c428cf17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'classifier_config',
        sa.Column('chroma_collection_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        'classifier_config',
        sa.Column('model_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.add_column(
        'classifier_config',
        sa.Column('use_params', sa.Boolean(), nullable=True),
    )
    op.create_foreign_key(
        "config_model",
        'classifier_config',
        'classifier_version',
        ['model_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("config_model", 'classifier_config', type_='foreignkey')
    op.drop_column('classifier_config', 'use_params')
    op.drop_column('classifier_config', 'model_id')
    op.drop_column('classifier_config', 'chroma_collection_name')
    # ### end Alembic commands ###
