"""used tokens table

Revision ID: c895fd49a34d
Revises: 81e06645ba0a
Create Date: 2024-07-19 14:56:55.896956

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c895fd49a34d"
down_revision: Union[str, None] = "078a8a1568f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "used_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tokens_count", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenant.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("tenant", "is_last")
    op.drop_column("tenant", "logo")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant",
        sa.Column("logo", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "tenant",
        sa.Column("is_last", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_table("used_token")
    # ### end Alembic commands ###
