"""add filepath column to column scheme

Revision ID: 72de143455bb
Revises: 58cef6fde2f9
Create Date: 2024-01-18 19:32:53.473599

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72de143455bb"
down_revision: Union[str, None] = "58cef6fde2f9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("file_path", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "file_path")
    # ### end Alembic commands ###
