"""create user roles and fix user tenants list

Revision ID: 859a2b44272f
Revises: c895fd49a34d
Create Date: 2024-07-23 20:02:07.727392

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "859a2b44272f"
down_revision: Union[str, None] = "c895fd49a34d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("user_tenant")
    op.add_column("user", sa.Column("tenant_id", sa.Integer(), nullable=True))
    op.add_column("user", sa.Column("role_id", sa.Integer(), nullable=True))
    op.create_foreign_key("user_role_id", "user", "role", ["role_id"], ["id"])
    op.create_foreign_key("user_tenant_id", "user", "tenant", ["tenant_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("user_role_id", "user", type_="foreignkey")
    op.drop_constraint("user_tenant_id", "user", type_="foreignkey")
    op.drop_column("user", "role_id")
    op.drop_column("user", "tenant_id")
    op.create_table(
        "user_tenant",
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenant.id"], name="user_tenant_tenant_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name="user_tenant_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("user_id", "tenant_id", name="user_tenant_pkey"),
    )
    op.drop_table("role")
    # ### end Alembic commands ###
