"""responsible users in orders classification config

Revision ID: bc83025e29ad
Revises: 6a2ae82fbecc
Create Date: 2025-01-28 17:57:12.947600

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "bc83025e29ad"
down_revision: Union[str, None] = "6a2ae82fbecc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_classification_config",
        sa.Column(
            "responsible_users",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_classification_config", "responsible_users")
    # ### end Alembic commands ###
