"""status for mapping iterations

Revision ID: 9eb4dc7442e2
Revises: bc83025e29ad
Create Date: 2025-02-28 15:02:58.601803

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9eb4dc7442e2"
down_revision: Union[str, None] = "bc83025e29ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "mapping_iteration",
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("mapping_iteration", "status")
    # ### end Alembic commands ###
