"""message templates in order classification config

Revision ID: 7c157a6bbb39
Revises: 9eb4dc7442e2
Create Date: 2025-03-11 16:21:15.533370

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c157a6bbb39"
down_revision: Union[str, None] = "9eb4dc7442e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_classification_config",
        sa.Column("is_use_send_message", sa.Boolean(), nullable=True),
    )
    op.add_column(
        "order_classification_config",
        sa.Column(
            "messages_templates",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_classification_config", "messages_templates")
    op.drop_column("order_classification_config", "is_use_send_message")
    # ### end Alembic commands ###
