"""orders tracking tasks

Revision ID: 478f4f152397
Revises: 7c157a6bbb39
Create Date: 2025-03-24 18:52:33.945196

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "478f4f152397"
down_revision: Union[str, None] = "7c157a6bbb39"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_tracking_task",
        sa.Column("config_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column(
            "last_order_details",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("internal_status", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("next_action", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "actions_logs",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("action_time", sa.DateTime(), nullable=True),
        sa.Column("is_completed", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["config_id"],
            ["order_classification_config.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_tracking_task")
    # ### end Alembic commands ###
