"""emergency classification history

Revision ID: 4ac076fff9f2
Revises: 93cde6304c50
Create Date: 2024-10-13 00:01:54.042740

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ac076fff9f2'
down_revision: Union[str, None] = '93cde6304c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# noinspection PyUnresolvedReferences
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'emergency_classification_history',
        sa.Column('is_error', sa.Boolean(), nullable=False),
        sa.Column('alert_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('alert_type_id', sa.Integer(), nullable=False),
        sa.Column('alert_timestamp', sa.Integer(), nullable=True),
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('order_status_id', sa.Integer(), nullable=False),
        sa.Column('order_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('order_normalized_query', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('order_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('order_emergency', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_emergency', sa.Boolean(), nullable=True),
        sa.Column('order_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('uds_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('order_update_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('order_update_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_classification_history')
    # ### end Alembic commands ###
