"""view-classification-in-classifier-config

Revision ID: 563015397e75
Revises: 041fa5e1dec7
Create Date: 2024-12-26 16:52:36.969068

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '563015397e75'
down_revision: Union[str, None] = '041fa5e1dec7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'classifier_config',
        sa.Column(
            'is_use_view_classification',
            sa.Boolean(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifier_config', 'is_use_view_classification')
    # ### end Alembic commands ###
