"""add chroma collection name to classifier config

Revision ID: 5b6d4f03a2d4
Revises: f79c428cf17b
Create Date: 2024-07-11 15:04:11.166793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5b6d4f03a2d4'
down_revision: Union[str, None] = 'f79c428cf17b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier_config', sa.Column('chroma_collection_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifier_config', 'chroma_collection_name')
    # ### end Alembic commands ###
