"""order classification config

Revision ID: 6e04c1d6e2f8
Revises: 93cde6304c50
Create Date: 2024-11-14 03:02:45.937237

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6e04c1d6e2f8'
down_revision: Union[str, None] = '93cde6304c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'order_classification_config',
        sa.Column('emergency_prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('client', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('is_use_emergency_classification', sa.Boolean(), nullable=True),
        sa.Column('is_use_order_updating', sa.Boolean(), nullable=True),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_classification_config')
    # ### end Alembic commands ###
