"""classifiers versions description field

Revision ID: 6f855d426c34
Revises: 838a0160e699
Create Date: 2024-04-23 19:38:22.801414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6f855d426c34'
down_revision: Union[str, None] = '838a0160e699'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier_version', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifier_version', 'description')
    # ### end Alembic commands ###
