"""add scheme column to prompt table

Revision ID: 838a0160e699
Revises: 07488a574e53
Create Date: 2024-03-31 22:53:27.312537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '838a0160e699'
down_revision: Union[str, None] = '2fb1c8ea4c04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt', sa.Column('scheme', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt', 'scheme')
    # ### end Alembic commands ###
