"""add nomenclatures_table_name to classifier config

Revision ID: 88435e18ac16
Revises: 859a2b44272f
Create Date: 2024-07-29 22:44:27.193048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '88435e18ac16'
down_revision: Union[str, None] = '859a2b44272f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('classifier_config', sa.Column('nomenclatures_table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('classifier_config', 'nomenclatures_table_name')
    # ### end Alembic commands ###
