"""message to resident params in orders classification config

Revision ID: b5032bfcf394
Revises: bc83025e29ad
Create Date: 2025-01-30 18:44:58.440911

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5032bfcf394'
down_revision: Union[str, None] = 'bc83025e29ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'order_classification_config',
        sa.Column(
            'is_send_message_to_resident',
            sa.Boolean(),
            nullable=True,
        ),
    )
    op.add_column(
        'order_classification_config',
        sa.Column(
            'message_to_resident_template',
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_classification_config', 'message_to_resident_template')
    op.drop_column('order_classification_config', 'is_send_message_to_resident')
    # ### end Alembic commands ###
