"""emergency classification config

Revision ID: fa72775b6804
Revises: 4ac076fff9f2
Create Date: 2024-10-13 01:09:28.670251

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fa72775b6804'
down_revision: Union[str, None] = '4ac076fff9f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'emergency_classification_config',
        sa.Column('is_use_emergency_classification', sa.Boolean(), nullable=False),
        sa.Column('is_use_order_updating', sa.Boolean(), nullable=False),
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_classification_config')
    # ### end Alembic commands ###
