import os

from dotenv import load_dotenv

load_dotenv()


class Environment:
    DEV = "development"
    PROD = "production"


ENVIRONMENT = os.getenv("ENVIRONMENT")
IS_DEV_ENV = ENVIRONMENT == Environment.DEV

NER_SERVICE_URL = os.getenv("NER_SERVICE_URL")

AZURE_DEPLOYMENT_NAME_DB_ASSISTANT = os.getenv("AZURE_DEPLOYMENT_NAME_DB_ASSISTANT")
AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES = os.getenv(
    "AZURE_DEPLOYMENT_NAME_SIMILAR_QUERIES"
)
AZURE_DEPLOYMENT_NAME_DOCS_ASSISTANT = os.getenv("AZURE_DEPLOYMENT_NAME_DOCS_ASSISTANT")
AZURE_DEPLOYMENT_NAME_EMBEDDINGS = os.getenv("AZURE_DEPLOYMENT_NAME_EMBEDDINGS")
AZURE_DEPLOYMENT_CIM_MAPPING = os.getenv("AZURE_DEPLOYMENT_CIM_MAPPING")
AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION = os.getenv(
    "AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION"
)

# Redis
REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = int(os.getenv("REDIS_PORT"))
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

# Chroma Vector Store
CHROMA_HOST = os.getenv("CHROMA_HOST")
CHROMA_PORT = os.getenv("CHROMA_PORT")

DB_CONNECTION_STRING = os.getenv("DB_CONNECTION_STRING")

DATA_FOLDER_PATH = os.getenv("DATA_FOLDER_PATH")

# Domyland Credentials
DOMYLAND_AUTH_EMAIL = os.getenv("DOMYLAND_AUTH_EMAIL")
DOMYLAND_AUTH_PASSWORD = os.getenv("DOMYLAND_AUTH_PASSWORD")
DOMYLAND_AUTH_TENANT_NAME = os.getenv("DOMYLAND_AUTH_TENANT_NAME")

# Vysota Azure OpenAI Credentials
VYSOTA_AZURE_OPENAI_ENDPOINT = os.getenv("VYSOTA_AZURE_OPENAI_ENDPOINT")
VYSOTA_AZURE_OPENAI_API_KEY = os.getenv("VYSOTA_AZURE_OPENAI_API_KEY")
VYSOTA_AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION = os.getenv(
    "VYSOTA_AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION"
)
