from infra.env import (
    VYSOTA_AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION,
    VYSOTA_AZURE_OPENAI_API_KEY,
    VYSOTA_AZURE_OPENAI_ENDPOINT,
)

ORDER_CLASSIFICATION_CLIENTS_CREDENTIALS = {
    "vysota": {
        "endpoint": VYSOTA_AZURE_OPENAI_ENDPOINT,
        "api_key": VYSOTA_AZURE_OPENAI_API_KEY,
        "deployment_name": VYSOTA_AZURE_DEPLOYMENT_NAME_ORDER_CLASSIFICATION,
    }
}
