name: 🚀 Deploy to Demostand

on:
  push:
    branches: [ "main" ]

jobs:

  pull_and_deploy:
    name: Update server by ssh
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          script: |
            cd ~/datastep-demo/demo-backend/
            git checkout main
            git pull

            echo "Stop containers"
            docker-compose stop backend rq-worker

            echo "Build new containers"
            docker-compose build backend rq-worker

            echo "Run new containers"
            docker-compose up -d backend rq-worker
