name: 🚀 Deploy to Demostand

on:
  push:
    branches: [ "main" ]

jobs:

  pull_and_deploy:
    name: Update server by ssh
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Connect and run script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script_stop: true
          script: |
            cd datastep-demo
            cd demo-backend
            git checkout main
            git pull
            
            echo "Build db_diagram"
            [ -d "./mermerd/" ] && rm -r ./mermerd
            curl -L https://github.com/KarnerTh/mermerd/releases/download/v0.10.0/mermerd_0.10.0_linux_amd64.tar.gz \
            -o mermerd_0.10.0_linux_arm64.tar.gz
            mkdir mermerd
            tar -xzvf mermerd_0.10.0_linux_arm64.tar.gz -C mermerd
            mermerd/mermerd -c ${{ secrets.DB_CONNECTION_STRING }} -o docs/db_diagram.md -s public \
            --useAllTables --encloseWithMermaidBackticks

            echo "Stop containers"
            docker-compose stop backend rq-worker

            echo "Build new containers"
            docker-compose build backend rq-worker

            echo "Run new containers"
            docker-compose up -d --build backend rq-worker
